sylius_metrika_index:
    pattern: /
    methods: [POST]
    defaults: { _controller: SyliusWebBundle:Frontend/Account/Metrika:index }

sylius_metrika_report:
    pattern: /{type}
    methods: [GET]
    defaults: { _controller: SyliusWebBundle:Frontend/Account/Metrika:report, type: day }
    requirements:
            type:  hour|day|week|month