# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_partial_product_latest:
    pattern: /latest
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            method: createFilterPaginator
            arguments: [$criteria, $sorting]
            template: $template
