# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_homepage:
    pattern: /
    defaults: { _controller: sylius.controller.frontend.homepage:mainAction }

sylius_remove_double:
    pattern: /remove_double/
    defaults: { _controller: sylius.controller.product:removeDoubleAction }

sylius_homepage2:
    pattern: /homepage
    defaults: { _controller: sylius.controller.frontend.homepage:main2Action }

sylius_search:
    pattern: /search
    defaults: { _controller: sylius.controller.frontend.homepage:searchAction }

sylius_backend_import_scan:
    pattern: /scan/
    defaults:
        _controller: sylius.controller.product:importScanAction

sylius_scan_code_articul:
    pattern: /scan/code_articul/
    defaults:
        _controller: sylius.controller.product:scanCodeArticulAction

sylius_scan_products:
    pattern: /scan/products/
    defaults:
        _controller: sylius.controller.product:scanProductsAction

sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /cart

sylius_cart_summary:
    pattern: /cart
    defaults:
        _controller: sylius.controller.cart:summaryAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:summary.html.twig

sylius_cart_save:
    pattern: /cart/save
    defaults:
        _controller: sylius.controller.cart:saveAction
        _sylius:
            template: SyliusWebBundle:Frontend/Cart:summary.html.twig

#Коллекции
sylius_collection_main:
    pattern: /collection
    defaults:
        _controller: sylius.controller.product:collectionAction

sylius_collections_main:
    pattern: /collections_
    defaults:
        _controller: sylius.controller.product:collectionsAction

sylius_silver_main:
    pattern: /silver_
    defaults: { _controller: sylius.controller.product:silverAction }

sylius_sale:
    pattern: /sale/{page}
    defaults: { _controller: sylius.controller.product:saleAction}

sylius_collections:
    pattern: /collections
    defaults: { _controller: sylius.controller.frontend.homepage:collectionsAction}

sylius_silver:
    pattern: /silver
    defaults: { _controller: sylius.controller.frontend.homepage:silverAction}

sylius_feedback:
    pattern: /feedback
    defaults: { _controller: sylius.controller.frontend.homepage:feedbackAction}

sylius_catalog:
    pattern: /catalog
    defaults: { _controller: sylius.controller.frontend.homepage:catalogAction}

sylius_currency:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/currency.yml
    prefix: /currency

sylius_product:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/product.yml

sylius_product_collections:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/productCollections.yml

sylius_page:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/page.yml
    prefix: /content

sylius_page_content:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/page_content.yml
    prefix: /page/

sylius_checkout:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/checkout.yml
    prefix: /checkout

sylius_account:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/account.yml
    prefix: /account

sylius_account_order_complete:
    pattern: /orders/complete
    methods: [GET]
    defaults: { _controller: SyliusWebBundle:Frontend/Account/Order:completeOrder }

sylius_account_order_email:
    pattern: /email
    methods: [GET]
    defaults: { _controller: SyliusWebBundle:Frontend/Account/Order:emailOrder }