sylius_page_show_content:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.page:showAction
        _sylius:
            template: SyliusWebBundle:Frontend/Page:showContent.html.twig
            method: findPage
            arguments: [$id]
    requirements:
        id: ".+"
