# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_product_index_by_taxon_collections:
    pattern: /collections/{page}/{category}
    defaults:
        _controller: sylius.controller.product:indexByTaxonAction
        _sylius:
            template: SyliusWebBundle:Frontend/Product:indexByTaxon.html.twig

sylius_product_index_by_taxon_product_collections:
    pattern: /collections/{page}/{category}/{slug}
    requirements:
         page:  \d+
    defaults:
        _controller: sylius.controller.product:indexByTaxonProductAction
        _sylius:
            template: SyliusWebBundle:Frontend/Product:indexByTaxon.html.twig

sylius_product_show_collections:
    pattern: /collections/p/{taxon}/{slug}
    defaults:
        _controller: sylius.controller.product:showFrontendAction
        _sylius:
            template: SyliusWebBundle:Frontend/Product:show.html.twig
            criteria: {slug: $slug}

sylius_product_show_collections_ajax:
    pattern: /collections/p/{taxon}/{slug}/{type}/
    defaults:
        _controller: sylius.controller.product:showFrontendAction
        _sylius:
            template: SyliusWebBundle:Frontend/Product:show.html.twig
            criteria: {slug: $slug}

sylius_product_show_collections_silver:
    pattern: /silver/p/{taxon}/{slug}
    defaults:
        _controller: sylius.controller.product:showFrontendAction
        _sylius:
            template: SyliusWebBundle:Frontend/Product:show.html.twig
            criteria: {slug: $slug}

sylius_product_show_collections_silver_ajax:
    pattern: /silver/p/{taxon}/{slug}/{type}/
    defaults:
        _controller: sylius.controller.product:showFrontendAction
        _sylius:
            template: SyliusWebBundle:Frontend/Product:show.html.twig
            criteria: {slug: $slug}

sylius_product_show_collections_accesories:
    pattern: /accesories/p/{taxon}/{slug}
    defaults:
        _controller: sylius.controller.product:showFrontendAction
        _sylius:
            template: SyliusWebBundle:Frontend/Product:show.html.twig
            criteria: {slug: $slug}

sylius_product_show_collections_accesories_ajax:
    pattern: /accesories/p/{taxon}/{slug}/{type}/
    defaults:
        _controller: sylius.controller.product:showFrontendAction
        _sylius:
            template: SyliusWebBundle:Frontend/Product:show.html.twig
            criteria: {slug: $slug}

#sylius_product_show_pushstate:
#    pattern: /{slug}
