# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_product_show:
    pattern: /catalog/p/{slug}
    defaults:
        _controller: sylius.controller.product:showFrontendAction
        _sylius:
            template: SyliusWebBundle:Frontend/Product:show.html.twig
            criteria: {slug: $slug}

sylius_product_index_by_taxon:
    pattern: /catalog/{page}/{category}
    defaults:
        _controller: sylius.controller.product:indexByTaxonAction
        _sylius:
            template: SyliusWebBundle:Frontend/Product:indexByTaxon.html.twig

sylius_product_index_by_taxon_product:
    pattern: /catalog/{page}/{category}/{slug}
    requirements:
         page:  \d+
    defaults:
        _controller: sylius.controller.product:indexByTaxonProductAction
        _sylius:
            template: SyliusWebBundle:Frontend/Product:indexByTaxon.html.twig

sylius_product_show_pushstate:
    pattern: /{slug}

sylius_product_slug_regenerate:
    pattern: /product/slug/regenerate/
    defaults:
        _controller: sylius.controller.product:slugRegenerateAction