# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_product_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Product:index.html.twig
            method: createFilterPaginator
            arguments: [$criteria, $sorting, $deleted]

sylius_backend_product_children_active:
    pattern: /children/active
    methods: [POST]
    defaults:
        _controller: sylius.controller.product:childrenActiveAction

sylius_backend_product_by_taxon:
    pattern: /children/taxon/{taxon}/{parent}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:productsTaxonAction

sylius_backend_product_children:
    pattern: /children/{parent}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:childrenAction

sylius_backend_product_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            template: SyliusWebBundle:Backend/Product:create.html.twig
            redirect: sylius_backend_product_show

sylius_backend_product_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: sylius.controller.product:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/Product:update.html.twig
            redirect: sylius_backend_product_show

sylius_backend_product_delete_all:
    pattern: /delete/all
    methods: [POST]
    defaults:
        _controller: sylius.controller.product:deleteAllAction

sylius_backend_product_edit_group:
    pattern: /edit/group
    methods: [POST]
    defaults:
        _controller: sylius.controller.product:editGroupAction

sylius_backend_product_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.product:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: sylius_backend_product_index

sylius_backend_product_history:
    pattern: /{id}/history
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:historyAction
        _sylius:
            template: SyliusWebBundle:Backend/Product:history.html.twig
            method: findForDetailsPage
            arguments: [$id]

sylius_backend_product_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:showAction
        _sylius:
            template: SyliusWebBundle:Backend/Product:show.html.twig
            method: findForDetailsPage
            arguments: [$id]

sylius_backend_product_change_order:
    pattern: /order_change/{drag}/{drop}/{type}
    defaults:
        _controller: sylius.controller.backend.dashboard:productOrderChangeAction

sylius_backend_product_reset_position:
    pattern: /reset_position/products/
    defaults:
        _controller: sylius.controller.backend.dashboard:productPositionResetAction