sylius_backend_slider_index:
    pattern: /
    defaults:
        _controller: sylius.controller.backend.dashboard:sliderAction
sylius_backend_slider_delete:
    pattern: /{id}
    defaults:
        _controller: sylius.controller.backend.dashboard:deleteSliderAction